#!/bin/bash

# Usage:
# ./add NAME FILE_PATH
#
# Example:
# ./add dialog-error '/home/user/materia-sound-theme/Materia/material_product_sounds/04 Secondary System Sounds/alert_error-01.wav'
#
# Tips:
# - NAME must follow http://0pointer.de/public/sound-naming-spec.html
# - NAME must be specified without any extension.
# - For FILE_PATH, it's recommended to drag and drop a file from the file manager to the terminal.

CURRENT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ "$1" =~ "."|"/" ]]; then
  echo "'$1' is an invalid name."
  exit 1
fi

ln -srf "$2" "$CURRENT_DIR/Materia/stereo/$1.wav"
